<a href="https://colab.research.google.com/github/amaansadat/PyTorch/blob/main/Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
#to find the derivative of a tensor, set requires_grad=true
x=torch.tensor(3.0,requires_grad=True)
y=x**2

In [ ]:
x

tensor(3., requires_grad=True)

In [ ]:
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(6.)

In [ ]:
import math
def dz_dx(x):
  return 2*x*math.cos(x**2)



In [ ]:
dz_dx(4)

-7.661275842587077

In [ ]:
#Now calculation derivative of tensor at x=4 in a different way than above 2 cells i.e by using autograd function
x=torch.tensor(4.0,requires_grad=True)
y=x**2
z=torch.sin(y)

In [ ]:
x

tensor(4., requires_grad=True)

In [ ]:
y

tensor(16., grad_fn=<PowBackward0>)

In [ ]:
z

tensor(-0.2879, grad_fn=<SinBackward0>)

In [ ]:
z.backward()

In [ ]:
x.grad

tensor(-7.6613)

In [ ]:
#by using autograd function it was way more easy than to write def dz_dx(x):return 2*x*math.cos(x**2) this mathematical function

In [18]:
#finding derivative of a neural network
import torch

In [2]:
# Inputs
x=torch.tensor(6.7)  # Input feature
y = torch.tensor(0.0)  # True label (binary)

w = torch.tensor(1.0)  # Weight
b = torch.tensor(0.0)  # Bias

In [3]:
# Binary Cross-Entropy Loss for scalar
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8  # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

In [4]:
# Forward pass
z = w * x + b  # Weighted sum (linear part)
y_pred = torch.sigmoid(z)  # Predicted probability

# Compute binary cross-entropy loss
loss = binary_cross_entropy_loss(y_pred, y)

In [5]:
loss

tensor(6.7012)

In [6]:
# Derivatives:
# 1. dL/d(y_pred): Loss with respect to the prediction (y_pred)
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))

# 2. dy_pred/dz: Prediction (y_pred) with respect to z (sigmoid derivative)
dy_pred_dz = y_pred * (1 - y_pred)

# 3. dz/dw and dz/db: z with respect to w and b
dz_dw = x  # dz/dw = x
dz_db = 1  # dz/db = 1 (bias contributes directly to z)

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [7]:
print(f"Manual Gradient of loss w.r.t weight (dw): {dL_dw}")
print(f"Manual Gradient of loss w.r.t bias (db): {dL_db}")

Manual Gradient of loss w.r.t weight (dw): 6.691762447357178
Manual Gradient of loss w.r.t bias (db): 0.998770534992218


In [8]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [9]:
#now finding same derivates using autograd(easy&short)

In [10]:
x=torch.tensor(6.7)
y = torch.tensor(0.0)

In [11]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [12]:
w

tensor(1., requires_grad=True)

In [14]:
b

tensor(0., requires_grad=True)

In [15]:
z = w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [16]:
#now calculating sigmoid
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [17]:
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [19]:
loss.backward()

In [21]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


In [22]:
#we can also create tensors as vector by using square brackets
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

In [23]:
x

tensor([1., 2., 3.], requires_grad=True)

In [24]:
y = (x**2).mean()  #formula
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [25]:
y.backward()

In [27]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [28]:
#Clearing Gradient=when we call backward function multiple times then our all of our gradients are accumulated together i.e previous outputs are added in new outputs as ans.
#So to not store our o/p's use x.grad.zero_() after displaying the gradient.

In [29]:
#disabling gradient tracking:should be done after training a neural network bcz then we need only forwardpass not .backward() bcz it occupies memory
#so the 3 ways to disable gradient tracking




In [30]:
#1)requires_grad_false
x.requires_grad_(False)
x

tensor([1., 2., 3.])

In [31]:
y = x ** 2
y

tensor([1., 4., 9.])

In [32]:
#now on calling y.backward() it'll not work&Error!

In [33]:
#2)using detach() function
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [34]:
z = x.detach()
z

tensor(2.)

In [35]:
y=z**2
y

tensor(4.)

In [37]:
#now y.backward() will show error

In [38]:
#Most convinient
#3)torch.no_grad()
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [39]:
with torch.no_grad():
  y=x**2


In [40]:
y

tensor(4.)

In [ ]:
#now y.backward() will shows error.