<a href="https://colab.research.google.com/github/amaansadat/PyTorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


CREATING A TENSOR

In [ ]:
#Using empty function
torch.empty(2,3)

tensor([[1.3563e-19, 2.7945e+20, 7.2133e+22],
        [1.9863e+29, 7.1854e+22, 7.5554e+28]])

In [ ]:
#using zeros function to create a tensor of zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones function to create tenor of ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand function to create a tenor of random values bw 0 to 1
torch.rand(2,3)

tensor([[0.5616, 0.2023, 0.2814],
        [0.5778, 0.3182, 0.5795]])

In [ ]:
#each time when we run rand function then output will be different and to preserve the value of rand we define a seed.
#manual_seed
torch.manual_seed(100)
torch.rand(2,3)
#now whenever we use this seed(100) to use rand function then each time we'll get the same values

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using tensor function to create a tensor of desired values
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#using arange function, lly to numpy
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

TENSOR SHAPES


In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [ ]:
#to create a tensor of same shape as given tensor use _like(giventensor) function i.e empty_like(x),ones_like(x) etc etc.
#And rand_like(x) will create same tensor only if given tensor has value bw 0 to 1 as rand function creates a tensor of value 0 to 1 so specify dtype=torch.float32

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.1126, 0.3590, 0.1562],
        [0.7051, 0.4210, 0.6422]])

TENSOR DATA TYPE

In [ ]:
#to find the datatype of tensor use x.dtype
x.dtype

torch.int64

In [ ]:
#to assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
#to change the datatype of existing tensor use to() function
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


MATHEMATICAL OPERATIONS IN TENSORS


### 1. Scalar operation

In [3]:
x = torch.rand(2,2)
x

tensor([[0.0924, 0.3690],
        [0.9555, 0.3823]])

In [6]:
#on adding a scalar: it'll be added in each element
x+2
#lly subtraction,multiplication,division
#int division
(x*100)//2
# mod
((x * 100)//2)%2
# power
x**2

tensor([[0.0085, 0.1361],
        [0.9130, 0.1461]])

### 2. Element wise operation

In [7]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2390, 0.8056, 0.3899],
        [0.8139, 0.4214, 0.9464]])
tensor([[0.5979, 0.2995, 0.2813],
        [0.2617, 0.9502, 0.3888]])


In [8]:
#add
a + b
#subtract
a - b
#multiply
a * b
#division
a / b
#power
a ** b
#mod
a % b

tensor([[0.2390, 0.2066, 0.1087],
        [0.0289, 0.4214, 0.1687]])

In [9]:
c = torch.tensor([1, -2, 3, -4])

In [10]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [11]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [12]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [13]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [16]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [17]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[4., 1., 4.],
        [7., 3., 8.]])

In [19]:
# sum of matrix
torch.sum(e)
# sum of columns
torch.sum(e, dim=0)
# sum of rows
torch.sum(e, dim=1)

tensor([ 9., 18.])

In [21]:
# mean(works only when datatype is float)
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([5.5000, 2.0000, 6.0000])

In [23]:
# argmax:tells position max element in tensor
torch.argmax(e)

tensor(5)

In [24]:
# argmin:tells position of min element in tensor
torch.argmin(e)

tensor(1)

In [25]:
# standard deviation
torch.std(e)

tensor(2.5884)

In [26]:
# variance
torch.var(e)

tensor(6.7000)

### 4. Matrix operations

In [27]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8, 5, 5],
        [4, 8, 4]])
tensor([[7, 4],
        [0, 2],
        [2, 3]])


In [28]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[66, 57],
        [36, 44]])

In [29]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [30]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[4., 5., 2.],
        [5., 6., 8.],
        [8., 0., 7.]])

In [31]:
# determinant
torch.det(h)

tensor(217.)

In [36]:
# relu:returns tensor containing positive values only
torch.relu(h)

tensor([[4., 5., 2.],
        [5., 6., 8.],
        [8., 0., 7.]])

In [32]:
# inverse
torch.inverse(h)

tensor([[ 0.1935, -0.1613,  0.1290],
        [ 0.1336,  0.0553, -0.1014],
        [-0.2212,  0.1843, -0.0046]])

 **Inplace** Operations:After any arithmetic operation we get ans in a new tensor but sometimes we need to change the current existing tensor,so we can do that using inplace operations.To make any operation inplace just use _ after it



In [34]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6243, 0.9428, 0.3178],
        [0.8143, 0.1762, 0.7642]])
tensor([[0.2020, 0.7650, 0.0564],
        [0.7002, 0.0377, 0.0958]])


In [35]:
m.add_(n)

tensor([[0.8263, 1.7078, 0.3742],
        [1.5145, 0.2139, 0.8600]])

## Copying a Tensor: use .clone() funcation


In [37]:
a = torch.rand(2,3)
a

tensor([[0.6321, 0.9073, 0.1549],
        [0.6146, 0.9390, 0.8338]])

In [38]:
b = a.clone()

In [39]:
a

tensor([[0.6321, 0.9073, 0.1549],
        [0.6146, 0.9390, 0.8338]])

In [40]:
b

tensor([[0.6321, 0.9073, 0.1549],
        [0.6146, 0.9390, 0.8338]])

In [41]:
a[0][0]=10

In [42]:
a

tensor([[10.0000,  0.9073,  0.1549],
        [ 0.6146,  0.9390,  0.8338]])

In [43]:
b

tensor([[0.6321, 0.9073, 0.1549],
        [0.6146, 0.9390, 0.8338]])

TENSOR OPERATIONS IN GPU

In [3]:
torch.cuda.is_available()

True

In [4]:
device=torch.device('cuda')

In [6]:
#creating new tensor on gpu
torch.rand((2,3), device=device)

tensor([[0.7338, 0.1702, 0.2735],
        [0.6523, 0.1262, 0.4267]], device='cuda:0')

In [8]:
#moving a existing cpu tensor to gpu
a=torch.rand(2,3)
a

tensor([[0.1976, 0.7822, 0.1725],
        [0.7930, 0.1285, 0.4849]])

In [9]:
a.to(device)

tensor([[0.1976, 0.7822, 0.1725],
        [0.7930, 0.1285, 0.4849]], device='cuda:0')

In [10]:
import time
#taking size of matrices as 1000
size=1000
# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)  # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)  # Matrix multiplication on GPU
torch.cuda.synchronize()  # Ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time on CPU: 0.0523 seconds
Time on GPU: 0.2073 seconds

Speedup (CPU time / GPU time): 0.2521534649195936


In [11]:
#unsqueeze function adds another dimension(1D i.e dimension of size 1) at desired place in an image dimesnion
c=torch.rand(226,226,3)
c.unsqueeze(0).shape   #it'll add another dimension 1 at 0th place


torch.Size([1, 226, 226, 3])

In [12]:
#squeeze function removes dimension of size=1 at desired place
x = torch.tensor([[[1, 2, 3]]])
print(x.shape)

torch.Size([1, 1, 3])


In [13]:
x = x.squeeze()  #after squeeze
print(x.shape)

torch.Size([3])
