<a href="https://colab.research.google.com/github/amaansadat/PyTorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
print(torch.__version__)

2.11.0+cu128


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


CREATING A TENSOR

In [8]:
#Using empty function
torch.empty(2,3)

tensor([[1.3563e-19, 2.7945e+20, 7.2133e+22],
        [1.9863e+29, 7.1854e+22, 7.5554e+28]])

In [11]:
#using zeros function to create a tensor of zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
#using ones function to create tenor of ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
#using rand function to create a tenor of random values bw 0 to 1
torch.rand(2,3)

tensor([[0.5616, 0.2023, 0.2814],
        [0.5778, 0.3182, 0.5795]])

In [14]:
#each time when we run rand function then output will be different and to preserve the value of rand we define a seed.
#manual_seed
torch.manual_seed(100)
torch.rand(2,3)
#now whenever we use this seed(100) to use rand function then each time we'll get the same values

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
#using tensor function to create a tensor of desired values
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
#using arange function, lly to numpy
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

TENSOR SHAPES


In [9]:
x=torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [3]:
#to create a tensor of same shape as given tensor use _like(giventensor) function i.e empty_like(x),ones_like(x) etc etc.
#And rand_like(x) will create same tensor only if given tensor has value bw 0 to 1 as rand function creates a tensor of value 0 to 1 so specify dtype=torch.float32

In [13]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.1126, 0.3590, 0.1562],
        [0.7051, 0.4210, 0.6422]])

TENSOR DATA TYPE

In [14]:
#to find the datatype of tensor use x.dtype
x.dtype

torch.int64

In [15]:
#to assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [16]:
#to change the datatype of existing tensor use to() function
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])